#
# Space Robotics Simulation, Phase 2
# Copyright (c) 2021, NASA-JSC. All Rights Reserved
# Unauthorized copying or distribution of this code is strictly prohibited
#
# 
# This message publishes the current score, and volatile collection state
# for this simulation
#
Header header

# scoop data
bool volatile_clod_mass # is volatile mass in scoop
bool regolith_clod_mass # is regolith mass in scoop