(cl:defpackage srcp2_msgs-msg
  (:use )
  (:export
   "<BATTERYSTATEMSG>"
   "BATTERYSTATEMSG"
   "<EXCAVATORSCOOPMSG>"
   "EXCAVATORSCOOPMSG"
   "<SCOREMSG>"
   "SCOREMSG"
   "<SYSTEMMONITORMSG>"
   "SYSTEMMONITORMSG"
   "<VOLSENSORMSG>"
   "VOLSENSORMSG"
  ))

