(cl:in-package srcp2_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          MAX_CAPACITY_WATT_HOURS-VAL
          MAX_CAPACITY_WATT_HOURS
          MAX_DISCHARGE_RATE_WATTS-VAL
          MAX_DISCHARGE_RATE_WATTS
          CURRENT_CAPACITY_WATT_HOURS-VAL
          CURRENT_CAPACITY_WATT_HOURS
          CURRENT_CONSUMPTION_WATTS-VAL
          CURRENT_CONSUMPTION_WATTS
          SAFE_MODE_AVAIL_FRAC-VAL
          SAFE_MODE_AVAIL_FRAC
          SAFE_MODE_PERCENT-VAL
          SAFE_MODE_PERCENT
          SHUTDOWN_PERCENT-VAL
          SHUTDOWN_PERCENT
          MODE-VAL
          MODE
          OVERLOAD-VAL
          OVERLOAD
          NUMBER_OF_CONNECTIONS-VAL
          NUMBER_OF_CONNECTIONS
))