// Generated by gencpp from file srcp2_msgs/BrakeRoverSrvRequest.msg
// DO NOT EDIT!


#ifndef SRCP2_MSGS_MESSAGE_BRAKEROVERSRVREQUEST_H
#define SRCP2_MSGS_MESSAGE_BRAKEROVERSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srcp2_msgs
{
template <class ContainerAllocator>
struct BrakeRoverSrvRequest_
{
  typedef BrakeRoverSrvRequest_<ContainerAllocator> Type;

  BrakeRoverSrvRequest_()
    : brake_force(0.0)  {
    }
  BrakeRoverSrvRequest_(const ContainerAllocator& _alloc)
    : brake_force(0.0)  {
  (void)_alloc;
    }



   typedef double _brake_force_type;
  _brake_force_type brake_force;





  typedef boost::shared_ptr< ::srcp2_msgs::BrakeRoverSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srcp2_msgs::BrakeRoverSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BrakeRoverSrvRequest_

typedef ::srcp2_msgs::BrakeRoverSrvRequest_<std::allocator<void> > BrakeRoverSrvRequest;

typedef boost::shared_ptr< ::srcp2_msgs::BrakeRoverSrvRequest > BrakeRoverSrvRequestPtr;
typedef boost::shared_ptr< ::srcp2_msgs::BrakeRoverSrvRequest const> BrakeRoverSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srcp2_msgs::BrakeRoverSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srcp2_msgs::BrakeRoverSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srcp2_msgs::BrakeRoverSrvRequest_<ContainerAllocator1> & lhs, const ::srcp2_msgs::BrakeRoverSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.brake_force == rhs.brake_force;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srcp2_msgs::BrakeRoverSrvRequest_<ContainerAllocator1> & lhs, const ::srcp2_msgs::BrakeRoverSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srcp2_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::srcp2_msgs::BrakeRoverSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srcp2_msgs::BrakeRoverSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srcp2_msgs::BrakeRoverSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srcp2_msgs::BrakeRoverSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srcp2_msgs::BrakeRoverSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srcp2_msgs::BrakeRoverSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srcp2_msgs::BrakeRoverSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1c5ffc183306e0f005a1347749c77564";
  }

  static const char* value(const ::srcp2_msgs::BrakeRoverSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1c5ffc183306e0f0ULL;
  static const uint64_t static_value2 = 0x05a1347749c77564ULL;
};

template<class ContainerAllocator>
struct DataType< ::srcp2_msgs::BrakeRoverSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srcp2_msgs/BrakeRoverSrvRequest";
  }

  static const char* value(const ::srcp2_msgs::BrakeRoverSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srcp2_msgs::BrakeRoverSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"# Space Robotics Simulation, Phase 2\n"
"# Copyright (c) 2019, NASA-JSC. All Rights Reserved\n"
"# Unauthorized copying or distribution of this code is strictly prohibited\n"
"#\n"
"float64 brake_force\n"
;
  }

  static const char* value(const ::srcp2_msgs::BrakeRoverSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srcp2_msgs::BrakeRoverSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.brake_force);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BrakeRoverSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srcp2_msgs::BrakeRoverSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srcp2_msgs::BrakeRoverSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "brake_force: ";
    Printer<double>::stream(s, indent + "  ", v.brake_force);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRCP2_MSGS_MESSAGE_BRAKEROVERSRVREQUEST_H
