// Generated by gencpp from file srcp2_msgs/BrakeRoverSrvResponse.msg
// DO NOT EDIT!


#ifndef SRCP2_MSGS_MESSAGE_BRAKEROVERSRVRESPONSE_H
#define SRCP2_MSGS_MESSAGE_BRAKEROVERSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srcp2_msgs
{
template <class ContainerAllocator>
struct BrakeRoverSrvResponse_
{
  typedef BrakeRoverSrvResponse_<ContainerAllocator> Type;

  BrakeRoverSrvResponse_()
    : finished(false)  {
    }
  BrakeRoverSrvResponse_(const ContainerAllocator& _alloc)
    : finished(false)  {
  (void)_alloc;
    }



   typedef uint8_t _finished_type;
  _finished_type finished;





  typedef boost::shared_ptr< ::srcp2_msgs::BrakeRoverSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srcp2_msgs::BrakeRoverSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BrakeRoverSrvResponse_

typedef ::srcp2_msgs::BrakeRoverSrvResponse_<std::allocator<void> > BrakeRoverSrvResponse;

typedef boost::shared_ptr< ::srcp2_msgs::BrakeRoverSrvResponse > BrakeRoverSrvResponsePtr;
typedef boost::shared_ptr< ::srcp2_msgs::BrakeRoverSrvResponse const> BrakeRoverSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srcp2_msgs::BrakeRoverSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srcp2_msgs::BrakeRoverSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srcp2_msgs::BrakeRoverSrvResponse_<ContainerAllocator1> & lhs, const ::srcp2_msgs::BrakeRoverSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.finished == rhs.finished;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srcp2_msgs::BrakeRoverSrvResponse_<ContainerAllocator1> & lhs, const ::srcp2_msgs::BrakeRoverSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srcp2_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::srcp2_msgs::BrakeRoverSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srcp2_msgs::BrakeRoverSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srcp2_msgs::BrakeRoverSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srcp2_msgs::BrakeRoverSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srcp2_msgs::BrakeRoverSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srcp2_msgs::BrakeRoverSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srcp2_msgs::BrakeRoverSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2797c797e620a950ba704492d72873b";
  }

  static const char* value(const ::srcp2_msgs::BrakeRoverSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2797c797e620a95ULL;
  static const uint64_t static_value2 = 0x0ba704492d72873bULL;
};

template<class ContainerAllocator>
struct DataType< ::srcp2_msgs::BrakeRoverSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srcp2_msgs/BrakeRoverSrvResponse";
  }

  static const char* value(const ::srcp2_msgs::BrakeRoverSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srcp2_msgs::BrakeRoverSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool finished\n"
;
  }

  static const char* value(const ::srcp2_msgs::BrakeRoverSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srcp2_msgs::BrakeRoverSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finished);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BrakeRoverSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srcp2_msgs::BrakeRoverSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srcp2_msgs::BrakeRoverSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "finished: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finished);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRCP2_MSGS_MESSAGE_BRAKEROVERSRVRESPONSE_H
