// Generated by gencpp from file srcp2_msgs/BrakeRoverSrv.msg
// DO NOT EDIT!


#ifndef SRCP2_MSGS_MESSAGE_BRAKEROVERSRV_H
#define SRCP2_MSGS_MESSAGE_BRAKEROVERSRV_H

#include <ros/service_traits.h>


#include <srcp2_msgs/BrakeRoverSrvRequest.h>
#include <srcp2_msgs/BrakeRoverSrvResponse.h>


namespace srcp2_msgs
{

struct BrakeRoverSrv
{

typedef BrakeRoverSrvRequest Request;
typedef BrakeRoverSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BrakeRoverSrv
} // namespace srcp2_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srcp2_msgs::BrakeRoverSrv > {
  static const char* value()
  {
    return "0c30799110874cd224d9a2d9de3215fc";
  }

  static const char* value(const ::srcp2_msgs::BrakeRoverSrv&) { return value(); }
};

template<>
struct DataType< ::srcp2_msgs::BrakeRoverSrv > {
  static const char* value()
  {
    return "srcp2_msgs/BrakeRoverSrv";
  }

  static const char* value(const ::srcp2_msgs::BrakeRoverSrv&) { return value(); }
};


// service_traits::MD5Sum< ::srcp2_msgs::BrakeRoverSrvRequest> should match
// service_traits::MD5Sum< ::srcp2_msgs::BrakeRoverSrv >
template<>
struct MD5Sum< ::srcp2_msgs::BrakeRoverSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srcp2_msgs::BrakeRoverSrv >::value();
  }
  static const char* value(const ::srcp2_msgs::BrakeRoverSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srcp2_msgs::BrakeRoverSrvRequest> should match
// service_traits::DataType< ::srcp2_msgs::BrakeRoverSrv >
template<>
struct DataType< ::srcp2_msgs::BrakeRoverSrvRequest>
{
  static const char* value()
  {
    return DataType< ::srcp2_msgs::BrakeRoverSrv >::value();
  }
  static const char* value(const ::srcp2_msgs::BrakeRoverSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srcp2_msgs::BrakeRoverSrvResponse> should match
// service_traits::MD5Sum< ::srcp2_msgs::BrakeRoverSrv >
template<>
struct MD5Sum< ::srcp2_msgs::BrakeRoverSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srcp2_msgs::BrakeRoverSrv >::value();
  }
  static const char* value(const ::srcp2_msgs::BrakeRoverSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srcp2_msgs::BrakeRoverSrvResponse> should match
// service_traits::DataType< ::srcp2_msgs::BrakeRoverSrv >
template<>
struct DataType< ::srcp2_msgs::BrakeRoverSrvResponse>
{
  static const char* value()
  {
    return DataType< ::srcp2_msgs::BrakeRoverSrv >::value();
  }
  static const char* value(const ::srcp2_msgs::BrakeRoverSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRCP2_MSGS_MESSAGE_BRAKEROVERSRV_H
