// Generated by gencpp from file srcp2_msgs/LocalizationSrv.msg
// DO NOT EDIT!


#ifndef SRCP2_MSGS_MESSAGE_LOCALIZATIONSRV_H
#define SRCP2_MSGS_MESSAGE_LOCALIZATIONSRV_H

#include <ros/service_traits.h>


#include <srcp2_msgs/LocalizationSrvRequest.h>
#include <srcp2_msgs/LocalizationSrvResponse.h>


namespace srcp2_msgs
{

struct LocalizationSrv
{

typedef LocalizationSrvRequest Request;
typedef LocalizationSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LocalizationSrv
} // namespace srcp2_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srcp2_msgs::LocalizationSrv > {
  static const char* value()
  {
    return "c102a4afb0b376754d6cb558ea05ea03";
  }

  static const char* value(const ::srcp2_msgs::LocalizationSrv&) { return value(); }
};

template<>
struct DataType< ::srcp2_msgs::LocalizationSrv > {
  static const char* value()
  {
    return "srcp2_msgs/LocalizationSrv";
  }

  static const char* value(const ::srcp2_msgs::LocalizationSrv&) { return value(); }
};


// service_traits::MD5Sum< ::srcp2_msgs::LocalizationSrvRequest> should match
// service_traits::MD5Sum< ::srcp2_msgs::LocalizationSrv >
template<>
struct MD5Sum< ::srcp2_msgs::LocalizationSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srcp2_msgs::LocalizationSrv >::value();
  }
  static const char* value(const ::srcp2_msgs::LocalizationSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srcp2_msgs::LocalizationSrvRequest> should match
// service_traits::DataType< ::srcp2_msgs::LocalizationSrv >
template<>
struct DataType< ::srcp2_msgs::LocalizationSrvRequest>
{
  static const char* value()
  {
    return DataType< ::srcp2_msgs::LocalizationSrv >::value();
  }
  static const char* value(const ::srcp2_msgs::LocalizationSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srcp2_msgs::LocalizationSrvResponse> should match
// service_traits::MD5Sum< ::srcp2_msgs::LocalizationSrv >
template<>
struct MD5Sum< ::srcp2_msgs::LocalizationSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srcp2_msgs::LocalizationSrv >::value();
  }
  static const char* value(const ::srcp2_msgs::LocalizationSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srcp2_msgs::LocalizationSrvResponse> should match
// service_traits::DataType< ::srcp2_msgs::LocalizationSrv >
template<>
struct DataType< ::srcp2_msgs::LocalizationSrvResponse>
{
  static const char* value()
  {
    return DataType< ::srcp2_msgs::LocalizationSrv >::value();
  }
  static const char* value(const ::srcp2_msgs::LocalizationSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRCP2_MSGS_MESSAGE_LOCALIZATIONSRV_H
