// Generated by gencpp from file srcp2_msgs/PidListSrv.msg
// DO NOT EDIT!


#ifndef SRCP2_MSGS_MESSAGE_PIDLISTSRV_H
#define SRCP2_MSGS_MESSAGE_PIDLISTSRV_H

#include <ros/service_traits.h>


#include <srcp2_msgs/PidListSrvRequest.h>
#include <srcp2_msgs/PidListSrvResponse.h>


namespace srcp2_msgs
{

struct PidListSrv
{

typedef PidListSrvRequest Request;
typedef PidListSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PidListSrv
} // namespace srcp2_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srcp2_msgs::PidListSrv > {
  static const char* value()
  {
    return "3f65269ed0f5642343d3d700bb52a4e0";
  }

  static const char* value(const ::srcp2_msgs::PidListSrv&) { return value(); }
};

template<>
struct DataType< ::srcp2_msgs::PidListSrv > {
  static const char* value()
  {
    return "srcp2_msgs/PidListSrv";
  }

  static const char* value(const ::srcp2_msgs::PidListSrv&) { return value(); }
};


// service_traits::MD5Sum< ::srcp2_msgs::PidListSrvRequest> should match
// service_traits::MD5Sum< ::srcp2_msgs::PidListSrv >
template<>
struct MD5Sum< ::srcp2_msgs::PidListSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srcp2_msgs::PidListSrv >::value();
  }
  static const char* value(const ::srcp2_msgs::PidListSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srcp2_msgs::PidListSrvRequest> should match
// service_traits::DataType< ::srcp2_msgs::PidListSrv >
template<>
struct DataType< ::srcp2_msgs::PidListSrvRequest>
{
  static const char* value()
  {
    return DataType< ::srcp2_msgs::PidListSrv >::value();
  }
  static const char* value(const ::srcp2_msgs::PidListSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srcp2_msgs::PidListSrvResponse> should match
// service_traits::MD5Sum< ::srcp2_msgs::PidListSrv >
template<>
struct MD5Sum< ::srcp2_msgs::PidListSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srcp2_msgs::PidListSrv >::value();
  }
  static const char* value(const ::srcp2_msgs::PidListSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srcp2_msgs::PidListSrvResponse> should match
// service_traits::DataType< ::srcp2_msgs::PidListSrv >
template<>
struct DataType< ::srcp2_msgs::PidListSrvResponse>
{
  static const char* value()
  {
    return DataType< ::srcp2_msgs::PidListSrv >::value();
  }
  static const char* value(const ::srcp2_msgs::PidListSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRCP2_MSGS_MESSAGE_PIDLISTSRV_H
