// Generated by gencpp from file srcp2_msgs/PidListSrvRequest.msg
// DO NOT EDIT!


#ifndef SRCP2_MSGS_MESSAGE_PIDLISTSRVREQUEST_H
#define SRCP2_MSGS_MESSAGE_PIDLISTSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srcp2_msgs
{
template <class ContainerAllocator>
struct PidListSrvRequest_
{
  typedef PidListSrvRequest_<ContainerAllocator> Type;

  PidListSrvRequest_()
    : show_list(false)  {
    }
  PidListSrvRequest_(const ContainerAllocator& _alloc)
    : show_list(false)  {
  (void)_alloc;
    }



   typedef uint8_t _show_list_type;
  _show_list_type show_list;





  typedef boost::shared_ptr< ::srcp2_msgs::PidListSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srcp2_msgs::PidListSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PidListSrvRequest_

typedef ::srcp2_msgs::PidListSrvRequest_<std::allocator<void> > PidListSrvRequest;

typedef boost::shared_ptr< ::srcp2_msgs::PidListSrvRequest > PidListSrvRequestPtr;
typedef boost::shared_ptr< ::srcp2_msgs::PidListSrvRequest const> PidListSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srcp2_msgs::PidListSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srcp2_msgs::PidListSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srcp2_msgs::PidListSrvRequest_<ContainerAllocator1> & lhs, const ::srcp2_msgs::PidListSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.show_list == rhs.show_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srcp2_msgs::PidListSrvRequest_<ContainerAllocator1> & lhs, const ::srcp2_msgs::PidListSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srcp2_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::srcp2_msgs::PidListSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srcp2_msgs::PidListSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srcp2_msgs::PidListSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srcp2_msgs::PidListSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srcp2_msgs::PidListSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srcp2_msgs::PidListSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srcp2_msgs::PidListSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d020193fe1203f15066d15c91bb7954";
  }

  static const char* value(const ::srcp2_msgs::PidListSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d020193fe1203f1ULL;
  static const uint64_t static_value2 = 0x5066d15c91bb7954ULL;
};

template<class ContainerAllocator>
struct DataType< ::srcp2_msgs::PidListSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srcp2_msgs/PidListSrvRequest";
  }

  static const char* value(const ::srcp2_msgs::PidListSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srcp2_msgs::PidListSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"# Space Robotics Simulation, Phase 2\n"
"# Copyright (c) 2020, NASA-JSC. All Rights Reserved\n"
"# Unauthorized copying or distribution of this code is strictly prohibited\n"
"#\n"
"bool     show_list    # shows all current PIDs of the rover's joints\n"
;
  }

  static const char* value(const ::srcp2_msgs::PidListSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srcp2_msgs::PidListSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.show_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PidListSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srcp2_msgs::PidListSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srcp2_msgs::PidListSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "show_list: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.show_list);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRCP2_MSGS_MESSAGE_PIDLISTSRVREQUEST_H
