// Generated by gencpp from file srcp2_msgs/PidTuningSrv.msg
// DO NOT EDIT!


#ifndef SRCP2_MSGS_MESSAGE_PIDTUNINGSRV_H
#define SRCP2_MSGS_MESSAGE_PIDTUNINGSRV_H

#include <ros/service_traits.h>


#include <srcp2_msgs/PidTuningSrvRequest.h>
#include <srcp2_msgs/PidTuningSrvResponse.h>


namespace srcp2_msgs
{

struct PidTuningSrv
{

typedef PidTuningSrvRequest Request;
typedef PidTuningSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PidTuningSrv
} // namespace srcp2_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srcp2_msgs::PidTuningSrv > {
  static const char* value()
  {
    return "759ddbd36fd49d58db11daa0b08fc8e1";
  }

  static const char* value(const ::srcp2_msgs::PidTuningSrv&) { return value(); }
};

template<>
struct DataType< ::srcp2_msgs::PidTuningSrv > {
  static const char* value()
  {
    return "srcp2_msgs/PidTuningSrv";
  }

  static const char* value(const ::srcp2_msgs::PidTuningSrv&) { return value(); }
};


// service_traits::MD5Sum< ::srcp2_msgs::PidTuningSrvRequest> should match
// service_traits::MD5Sum< ::srcp2_msgs::PidTuningSrv >
template<>
struct MD5Sum< ::srcp2_msgs::PidTuningSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srcp2_msgs::PidTuningSrv >::value();
  }
  static const char* value(const ::srcp2_msgs::PidTuningSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srcp2_msgs::PidTuningSrvRequest> should match
// service_traits::DataType< ::srcp2_msgs::PidTuningSrv >
template<>
struct DataType< ::srcp2_msgs::PidTuningSrvRequest>
{
  static const char* value()
  {
    return DataType< ::srcp2_msgs::PidTuningSrv >::value();
  }
  static const char* value(const ::srcp2_msgs::PidTuningSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srcp2_msgs::PidTuningSrvResponse> should match
// service_traits::MD5Sum< ::srcp2_msgs::PidTuningSrv >
template<>
struct MD5Sum< ::srcp2_msgs::PidTuningSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srcp2_msgs::PidTuningSrv >::value();
  }
  static const char* value(const ::srcp2_msgs::PidTuningSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srcp2_msgs::PidTuningSrvResponse> should match
// service_traits::DataType< ::srcp2_msgs::PidTuningSrv >
template<>
struct DataType< ::srcp2_msgs::PidTuningSrvResponse>
{
  static const char* value()
  {
    return DataType< ::srcp2_msgs::PidTuningSrv >::value();
  }
  static const char* value(const ::srcp2_msgs::PidTuningSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRCP2_MSGS_MESSAGE_PIDTUNINGSRV_H
