// Generated by gencpp from file srcp2_msgs/SpotLightSrv.msg
// DO NOT EDIT!


#ifndef SRCP2_MSGS_MESSAGE_SPOTLIGHTSRV_H
#define SRCP2_MSGS_MESSAGE_SPOTLIGHTSRV_H

#include <ros/service_traits.h>


#include <srcp2_msgs/SpotLightSrvRequest.h>
#include <srcp2_msgs/SpotLightSrvResponse.h>


namespace srcp2_msgs
{

struct SpotLightSrv
{

typedef SpotLightSrvRequest Request;
typedef SpotLightSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SpotLightSrv
} // namespace srcp2_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srcp2_msgs::SpotLightSrv > {
  static const char* value()
  {
    return "e98a2777615dc21bee2bf971bff096b4";
  }

  static const char* value(const ::srcp2_msgs::SpotLightSrv&) { return value(); }
};

template<>
struct DataType< ::srcp2_msgs::SpotLightSrv > {
  static const char* value()
  {
    return "srcp2_msgs/SpotLightSrv";
  }

  static const char* value(const ::srcp2_msgs::SpotLightSrv&) { return value(); }
};


// service_traits::MD5Sum< ::srcp2_msgs::SpotLightSrvRequest> should match
// service_traits::MD5Sum< ::srcp2_msgs::SpotLightSrv >
template<>
struct MD5Sum< ::srcp2_msgs::SpotLightSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srcp2_msgs::SpotLightSrv >::value();
  }
  static const char* value(const ::srcp2_msgs::SpotLightSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srcp2_msgs::SpotLightSrvRequest> should match
// service_traits::DataType< ::srcp2_msgs::SpotLightSrv >
template<>
struct DataType< ::srcp2_msgs::SpotLightSrvRequest>
{
  static const char* value()
  {
    return DataType< ::srcp2_msgs::SpotLightSrv >::value();
  }
  static const char* value(const ::srcp2_msgs::SpotLightSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srcp2_msgs::SpotLightSrvResponse> should match
// service_traits::MD5Sum< ::srcp2_msgs::SpotLightSrv >
template<>
struct MD5Sum< ::srcp2_msgs::SpotLightSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srcp2_msgs::SpotLightSrv >::value();
  }
  static const char* value(const ::srcp2_msgs::SpotLightSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srcp2_msgs::SpotLightSrvResponse> should match
// service_traits::DataType< ::srcp2_msgs::SpotLightSrv >
template<>
struct DataType< ::srcp2_msgs::SpotLightSrvResponse>
{
  static const char* value()
  {
    return DataType< ::srcp2_msgs::SpotLightSrv >::value();
  }
  static const char* value(const ::srcp2_msgs::SpotLightSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRCP2_MSGS_MESSAGE_SPOTLIGHTSRV_H
