// Generated by gencpp from file srcp2_msgs/SystemPowerSaveSrv.msg
// DO NOT EDIT!


#ifndef SRCP2_MSGS_MESSAGE_SYSTEMPOWERSAVESRV_H
#define SRCP2_MSGS_MESSAGE_SYSTEMPOWERSAVESRV_H

#include <ros/service_traits.h>


#include <srcp2_msgs/SystemPowerSaveSrvRequest.h>
#include <srcp2_msgs/SystemPowerSaveSrvResponse.h>


namespace srcp2_msgs
{

struct SystemPowerSaveSrv
{

typedef SystemPowerSaveSrvRequest Request;
typedef SystemPowerSaveSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SystemPowerSaveSrv
} // namespace srcp2_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srcp2_msgs::SystemPowerSaveSrv > {
  static const char* value()
  {
    return "7952b3919e8de2c1fd024be9ea064cf1";
  }

  static const char* value(const ::srcp2_msgs::SystemPowerSaveSrv&) { return value(); }
};

template<>
struct DataType< ::srcp2_msgs::SystemPowerSaveSrv > {
  static const char* value()
  {
    return "srcp2_msgs/SystemPowerSaveSrv";
  }

  static const char* value(const ::srcp2_msgs::SystemPowerSaveSrv&) { return value(); }
};


// service_traits::MD5Sum< ::srcp2_msgs::SystemPowerSaveSrvRequest> should match
// service_traits::MD5Sum< ::srcp2_msgs::SystemPowerSaveSrv >
template<>
struct MD5Sum< ::srcp2_msgs::SystemPowerSaveSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srcp2_msgs::SystemPowerSaveSrv >::value();
  }
  static const char* value(const ::srcp2_msgs::SystemPowerSaveSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srcp2_msgs::SystemPowerSaveSrvRequest> should match
// service_traits::DataType< ::srcp2_msgs::SystemPowerSaveSrv >
template<>
struct DataType< ::srcp2_msgs::SystemPowerSaveSrvRequest>
{
  static const char* value()
  {
    return DataType< ::srcp2_msgs::SystemPowerSaveSrv >::value();
  }
  static const char* value(const ::srcp2_msgs::SystemPowerSaveSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srcp2_msgs::SystemPowerSaveSrvResponse> should match
// service_traits::MD5Sum< ::srcp2_msgs::SystemPowerSaveSrv >
template<>
struct MD5Sum< ::srcp2_msgs::SystemPowerSaveSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srcp2_msgs::SystemPowerSaveSrv >::value();
  }
  static const char* value(const ::srcp2_msgs::SystemPowerSaveSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srcp2_msgs::SystemPowerSaveSrvResponse> should match
// service_traits::DataType< ::srcp2_msgs::SystemPowerSaveSrv >
template<>
struct DataType< ::srcp2_msgs::SystemPowerSaveSrvResponse>
{
  static const char* value()
  {
    return DataType< ::srcp2_msgs::SystemPowerSaveSrv >::value();
  }
  static const char* value(const ::srcp2_msgs::SystemPowerSaveSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRCP2_MSGS_MESSAGE_SYSTEMPOWERSAVESRV_H
