// Generated by gencpp from file srcp2_msgs/SystemPowerSaveSrvResponse.msg
// DO NOT EDIT!


#ifndef SRCP2_MSGS_MESSAGE_SYSTEMPOWERSAVESRVRESPONSE_H
#define SRCP2_MSGS_MESSAGE_SYSTEMPOWERSAVESRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srcp2_msgs
{
template <class ContainerAllocator>
struct SystemPowerSaveSrvResponse_
{
  typedef SystemPowerSaveSrvResponse_<ContainerAllocator> Type;

  SystemPowerSaveSrvResponse_()
    : success(false)
    , message()  {
    }
  SystemPowerSaveSrvResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::srcp2_msgs::SystemPowerSaveSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srcp2_msgs::SystemPowerSaveSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SystemPowerSaveSrvResponse_

typedef ::srcp2_msgs::SystemPowerSaveSrvResponse_<std::allocator<void> > SystemPowerSaveSrvResponse;

typedef boost::shared_ptr< ::srcp2_msgs::SystemPowerSaveSrvResponse > SystemPowerSaveSrvResponsePtr;
typedef boost::shared_ptr< ::srcp2_msgs::SystemPowerSaveSrvResponse const> SystemPowerSaveSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srcp2_msgs::SystemPowerSaveSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srcp2_msgs::SystemPowerSaveSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srcp2_msgs::SystemPowerSaveSrvResponse_<ContainerAllocator1> & lhs, const ::srcp2_msgs::SystemPowerSaveSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srcp2_msgs::SystemPowerSaveSrvResponse_<ContainerAllocator1> & lhs, const ::srcp2_msgs::SystemPowerSaveSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srcp2_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::srcp2_msgs::SystemPowerSaveSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srcp2_msgs::SystemPowerSaveSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srcp2_msgs::SystemPowerSaveSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srcp2_msgs::SystemPowerSaveSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srcp2_msgs::SystemPowerSaveSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srcp2_msgs::SystemPowerSaveSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srcp2_msgs::SystemPowerSaveSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::srcp2_msgs::SystemPowerSaveSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::srcp2_msgs::SystemPowerSaveSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srcp2_msgs/SystemPowerSaveSrvResponse";
  }

  static const char* value(const ::srcp2_msgs::SystemPowerSaveSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srcp2_msgs::SystemPowerSaveSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
;
  }

  static const char* value(const ::srcp2_msgs::SystemPowerSaveSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srcp2_msgs::SystemPowerSaveSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SystemPowerSaveSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srcp2_msgs::SystemPowerSaveSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srcp2_msgs::SystemPowerSaveSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRCP2_MSGS_MESSAGE_SYSTEMPOWERSAVESRVRESPONSE_H
